# /app /usr /lib
# FROM --platform=linux/amd64 node:19-alpine3.16
FROM --platform=$BUILDPLATFORM node:19-alpine3.16

#cd /app
WORKDIR /app

#Dest /app
COPY package.json ./

#Install dependencies
RUN npm install

#Dest /app
COPY . .

# Realizar tests
RUN npm run test

#Eliminar archivos y directorios innecesarios
RUN rm -rf tests && rm -rf node_modules

#Unicamente dependencias de produccion
RUN npm install --prod

# Comando run de la imagen
CMD ["node", "app.js"]